version: '3.8'
services:
    app:
        build: .
        container_name: app
        restart: always
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        volumes:
            - ./:/var/www/html/
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - app-network
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html/
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network
        environment:
            - NGINX_HOST=localhost
        depends_on:
            - app
            - db
    db:
        image: mysql:8.3.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: donteco
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql/init:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
        networks:
            - app-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8090:80
        environment:
            PMA_HOST: db
        depends_on:
            - db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
